image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64

build_script:
- cmd: >-
    npm i

    npm run electron:build-win

test: off

artifacts:
- path: dist_electron/phpcoin-wallet 1.0.0.exe
  name: phpcoin-wallet.exe
